kind: pipeline
name: Signature Drone

steps:
 - name: compile
   image: fajar4561/saciku:latest
   environment:
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     TG_TOKEN:
       from_secret: TG_TOKEN
     AWAL:
       from_secret: AWAL
     AKHIR:
       from_secret: AKHIR
   commands:
      - git config --global user.name "$AWAL"
      - git config --global user.email "abenkkenari@gmail.com"
      - git clone https://$AWAL:$AKHIR@github.com/HoleDroid/link -b stock kernel && cd kernel
      - curl https://raw.githubusercontent.com/HoleDroid/kernel-builder-drone/master/build.sh > run.sh
      - bash run.sh
