kind: pipeline
name: Signature Drone

steps:
 - name: compile
   image: ubuntu:20.04
   environment:
     
   commands:
      - git config --global user.name "fajar4561"
      - git config --global user.email "maulanafajar751@gmail.com"
      - git clone https://github.com/fajar4561/Signature-Kernel-CAF.git -b master kernel && cd kernel
      - curl https://raw.githubusercontent.com/fajar4561/myscripts/master/sotod/caf.sh > run.sh
      - source run.sh
